<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // ✅ This is important

class DistributorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
public function run(): void
    {
  DB::table('distributors')->insert([
            [
                'id' => 1,
                'sales_persons_id' => 1,
                'appointment_date' => '2025-07-25',
                'firm_name' => 'K.A Tradings',
                'nature_of_firm' => 'Proprietorship',
                'address_line_1' => 'VIP Road',
                'address_line_2' => 'Chandan Nagar',
                'town' => 'Guwahati',
                'district' => 'Kamrup',
                'state' => 'Assam',
                'pincode' => '781037',
                'landmark' => 'Near Sai Baba Mandir',
                'latitude' => null,
                'longitude' => null,
                'contact_person' => 'Nazrul Islam',
                'designation_contact' => 'Proprietor',
                'contact_number' => '9101317080',
                'email' => 'mazibur@prrahi.in',
                'gst' => '00',
                'date_of_birth' => '1994-01-01',
                'date_of_anniversary' => '2016-12-26',
                'profile_photo' => null,
                'login_id' => 'katradings@12',
                'password' => '$2y$12$NxPs.8KPBawXPNVpZ/wvxu7rsD.E9NW/QCsTOXGXwzAdAYd6ynZ5u',
                'created_at' => '2025-08-11 15:43:09',
                'updated_at' => '2025-08-11 15:43:09',
            ],
            [
                'id' => 2,
                'sales_persons_id' => 1,
                'appointment_date' => '2025-07-08',
                'firm_name' => 'Shristi Associates',
                'nature_of_firm' => 'Proprietorship',
                'address_line_1' => 'Apurba Sinha Path',
                'address_line_2' => 'Zoo Road Tiniali, Guwahati',
                'town' => 'Guwahati',
                'district' => 'Kamrup',
                'state' => 'Assam',
                'pincode' => '781024',
                'landmark' => 'Apurba Sinha Path',
                'latitude' => null,
                'longitude' => null,
                'contact_person' => 'B. Bhattacharjee',
                'designation_contact' => 'Owner',
                'contact_number' => '9435106106',
                'email' => 'shristiassociates@gmail.com',
                'gst' => '18AGYPB5789PZ1',
                'date_of_birth' => '1965-01-01',
                'date_of_anniversary' => '1991-01-21',
                'profile_photo' => null,
                'login_id' => 'shristiassociates@12',
                'password' => '$2y$12$QP5ujVS.Lm3QopeYx4uKHuxFkPa5MztJhecanD5rRX1II2vgHLT0.',
                'created_at' => '2025-08-11 17:38:47',
                'updated_at' => '2025-08-11 17:38:47',
            ],
            [
                'id' => 3,
                'sales_persons_id' => 1,
                'appointment_date' => '2025-07-30',
                'firm_name' => 'Manisha Enterprise',
                'nature_of_firm' => 'Proprietorship',
                'address_line_1' => 'Mangaldai, Nataye, Mandir Road',
                'address_line_2' => 'Ward No.1',
                'town' => 'Mangaldai',
                'district' => 'Darrang',
                'state' => 'Assam',
                'pincode' => '784125',
                'landmark' => 'Near District Library',
                'latitude' => null,
                'longitude' => null,
                'contact_person' => 'Raj Jyoti Deka',
                'designation_contact' => 'Owner',
                'contact_number' => '8876682585',
                'email' => 'manishaenterprise@gmail.com',
                'gst' => '18BILPD4789F1ZW',
                'date_of_birth' => '1991-12-29',
                'date_of_anniversary' => '2023-11-28',
                'profile_photo' => null,
                'login_id' => 'manishaenterprise@12',
                'password' => '$2y$12$lePNQLlqPFbJLQjWm8R2d.S98lwXJVcfKxBY5CDA1BmT9kdiifezq',
                'created_at' => '2025-08-11 17:46:19',
                'updated_at' => '2025-08-11 17:46:19',
            ],
            [
                'id' => 7,
                'sales_persons_id' => null,
                'appointment_date' => '2025-07-28',
                'firm_name' => 'Shree Bhawani Trading Co.',
                'nature_of_firm' => 'Proprietorship',
                'address_line_1' => 'Sonitpur, Tezpur',
                'address_line_2' => null,
                'town' => 'Sonitpur',
                'district' => 'Tezpur',
                'state' => 'Assam',
                'pincode' => '784001',
                'landmark' => null,
                'latitude' => null,
                'longitude' => null,
                'contact_person' => 'Paresh Kumar Sharma',
                'designation_contact' => 'Proprietor',
                'contact_number' => '9435082247',
                'email' => 'sbtctzp01@gmail.com',
                'gst' => '18AOKPS6973G1Z7',
                'date_of_birth' => '1963-01-01',
                'date_of_anniversary' => '1980-12-10',
                'profile_photo' => null,
                'login_id' => 'shree1234',
                'password' => '$2y$12$PBWN0.bnFxD7fSxBxIBzNubc8G3NveD8OynbDrCnlPEV.e48.mQ2O',
                'created_at' => '2025-08-18 20:53:31',
                'updated_at' => '2025-08-18 20:53:31',
            ],
            [
                'id' => 8,
                'sales_persons_id' => null,
                'appointment_date' => '2025-07-18',
                'firm_name' => 'M/S Maitri Enterprise',
                'nature_of_firm' => 'Proprietorship',
                'address_line_1' => 'Gol  Bazar',
                'address_line_2' => 'Netaji Market',
                'town' => 'Agartala',
                'district' => 'West Tripura',
                'state' => 'Tripura',
                'pincode' => '799001',
                'landmark' => 'Near Netaji Market gate No 3',
                'latitude' => null,
                'longitude' => null,
                'contact_person' => 'Saruv Paul',
                'designation_contact' => 'Proprietor',
                'contact_number' => '8974756354',
                'email' => null,
                'gst' => '16EWGPP1107R1Z3',
                'date_of_birth' => '2000-07-11',
                'date_of_anniversary' => null,
                'profile_photo' => null,
                'login_id' => 'msmaitrienterprise@123',
                'password' => '$2y$12$vc0A0akQiXOWMmAr9Mk.eeGiHUuUln1R4Hjwdc521yO.3R.y.X1Ry',
                'created_at' => '2025-08-22 05:27:42',
                'updated_at' => '2025-08-22 05:49:44',
            ],
            [
                'id' => 9,
                'sales_persons_id' => null,
                'appointment_date' => '2025-07-21',
                'firm_name' => 'M/s Baba Loknath Enterprise',
                'nature_of_firm' => 'Proprietorship',
                'address_line_1' => 'Jatindra Sarani',
                'address_line_2' => 'Madhya Nayapara',
                'town' => 'Dharmanagar',
                'district' => 'North Tripura',
                'state' => 'Tripura',
                'pincode' => '799205',
                'landmark' => 'Near Royal Enfiled Sowroom',
                'latitude' => 26.1554176,
                'longitude' => 91.7831680,
                'contact_person' => 'Anirban Chanda',
                'designation_contact' => 'Proprietor',
                'contact_number' => '88372-59532',
                'email' => 'anirbanchanda10@gmail.com',
                'gst' => '16AZBPC5547Q1Z1',
                'date_of_birth' => '1990-02-08',
                'date_of_anniversary' => '2013-09-07',
                'profile_photo' => null,
                'login_id' => 'msbabaloknathenterprise@123',
                'password' => '$2y$12$v8OcFMSlJXx5ek55chmyiOzI5am/OI7xus4p.BNkbUUNOdRLImtRK',
                'created_at' => '2025-08-22 05:34:59',
                'updated_at' => '2025-09-01 03:33:26',
            ],
            [
                'id' => 10,
                'sales_persons_id' => null,
                'appointment_date' => '2025-07-22',
                'firm_name' => 'Ms Kalpana Store',
                'nature_of_firm' => 'Proprietorship',
                'address_line_1' => 'Pabiachara',
                'address_line_2' => 'Kumarghat',
                'town' => 'Kumarghat',
                'district' => 'Unokuti',
                'state' => 'Tripura',
                'pincode' => '799264',
                'landmark' => 'Near Canara Bank Kumarghat',
                'latitude' => null,
                'longitude' => null,
                'contact_person' => 'Bablu Paul',
                'designation_contact' => 'Proprietor',
                'contact_number' => '9436477557',
                'email' => 'paulbablukgt@gmail.com',
                'gst' => '16BPTPP3805B1ZV',
                'date_of_birth' => '1982-05-07',
                'date_of_anniversary' => '2013-09-07',
                'profile_photo' => null,
                'login_id' => 'mskalpanastore',
                'password' => '$2y$12$/uWzvCWXxLiojfh8V8QhvOcqnTzNccHaIktbOAKeKOBG/wJAoagVC',
                'created_at' => '2025-09-02 01:01:36',
                'updated_at' => '2025-09-02 01:01:36',
            ],
        ]);

    }

}
