<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // ✅ This is important

class DistributorCompanies extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

DB::table('distributor_companies')->insert([
            [
                'id' => 1,
                'distributor_id' => 1,
                'company_name' => 'EVERADY',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 15:43:09',
                'updated_at' => '2025-08-11 15:43:09',
            ],
            [
                'id' => 2,
                'distributor_id' => 1,
                'company_name' => 'Zed Black',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 15:43:09',
                'updated_at' => '2025-08-11 15:43:09',
            ],
            [
                'id' => 3,
                'distributor_id' => 1,
                'company_name' => 'Paran',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 15:43:09',
                'updated_at' => '2025-08-11 15:43:09',
            ],
            [
                'id' => 4,
                'distributor_id' => 2,
                'company_name' => 'SHREE BAIDYANTTI',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 17:38:47',
                'updated_at' => '2025-08-11 17:38:47',
            ],
            [
                'id' => 5,
                'distributor_id' => 2,
                'company_name' => 'Universal',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 17:38:47',
                'updated_at' => '2025-08-11 17:38:47',
            ],
            [
                'id' => 6,
                'distributor_id' => 2,
                'company_name' => 'Mahar',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 17:38:47',
                'updated_at' => '2025-08-11 17:38:47',
            ],
            [
                'id' => 7,
                'distributor_id' => 2,
                'company_name' => 'T.T.F',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 17:38:47',
                'updated_at' => '2025-08-11 17:38:47',
            ],
            [
                'id' => 8,
                'distributor_id' => 2,
                'company_name' => 'Malhutra Mkt',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 17:38:47',
                'updated_at' => '2025-08-11 17:38:47',
            ],
            [
                'id' => 9,
                'distributor_id' => 3,
                'company_name' => 'DS GROUP',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-11 17:46:19',
                'updated_at' => '2025-08-11 17:46:19',
            ],
            [
                'id' => 18,
                'distributor_id' => 8,
                'company_name' => 'Shalimar',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-22 05:49:44',
                'updated_at' => '2025-08-22 05:49:44',
            ],
            [
                'id' => 19,
                'distributor_id' => 8,
                'company_name' => 'Everady',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-22 05:49:44',
                'updated_at' => '2025-08-22 05:49:44',
            ],
            [
                'id' => 20,
                'distributor_id' => 8,
                'company_name' => 'Mahesh Adiboil',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-08-22 05:49:44',
                'updated_at' => '2025-08-22 05:49:44',
            ],
            [
                'id' => 21,
                'distributor_id' => 9,
                'company_name' => 'Britannia',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-09-01 03:33:26',
                'updated_at' => '2025-09-01 03:33:26',
            ],
            [
                'id' => 22,
                'distributor_id' => 9,
                'company_name' => 'Perfetti',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-09-01 03:33:26',
                'updated_at' => '2025-09-01 03:33:26',
            ],
            [
                'id' => 23,
                'distributor_id' => 9,
                'company_name' => 'Cycle',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-09-01 03:33:26',
                'updated_at' => '2025-09-01 03:33:26',
            ],
            [
                'id' => 24,
                'distributor_id' => 9,
                'company_name' => 'Moyora',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-09-01 03:33:26',
                'updated_at' => '2025-09-01 03:33:26',
            ],
            [
                'id' => 25,
                'distributor_id' => 9,
                'company_name' => 'Bikaji',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-09-01 03:33:26',
                'updated_at' => '2025-09-01 03:33:26',
            ],
            [
                'id' => 26,
                'distributor_id' => 10,
                'company_name' => 'Colgate',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-09-02 01:01:36',
                'updated_at' => '2025-09-02 01:01:36',
            ],
            [
                'id' => 27,
                'distributor_id' => 10,
                'company_name' => 'Fenna',
                'segment' => null,
                'brand_name' => null,
                'products' => null,
                'working_as' => null,
                'margin' => null,
                'payment_terms' => null,
                'working_since' => null,
                'area_operation' => null,
                'monthly_to' => null,
                'dsr_no' => null,
                'details' => null,
                'created_at' => '2025-09-02 01:01:36',
                'updated_at' => '2025-09-02 01:01:36',
            ],
        ]);



    }



}
