<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // ✅ This is important

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('products')->delete();
        
        DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => NULL,
                'name' => 'Brahmos',
                'code' => NULL,
                'type' => 'simple',
                'category_id' => 12,
                'sub_category_id' => NULL,
                'base_unit' => 'case',
                'base_quantity' => 100,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '100.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '86.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => '9',
                'attributes' => NULL,
                'created_at' => '2025-12-24 19:55:54',
                'updated_at' => '2025-12-24 19:55:54',
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => NULL,
                'name' => 'Cup Sambrani',
                'code' => '75CUP3in1',
                'type' => 'simple',
                'category_id' => 9,
                'sub_category_id' => NULL,
                'base_unit' => 'case',
                'base_quantity' => 12,
                'mrp_per_unit' => '75.00',
                'ptr_per_dozen' => '650.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '562.77',
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => '4',
                'attributes' => NULL,
                'created_at' => '2025-12-24 20:02:42',
                'updated_at' => '2025-12-24 20:02:42',
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => NULL,
                'name' => 'Dhup Stick 4"',
                'code' => '15DHUPSTICK',
                'type' => 'simple',
                'category_id' => 10,
                'sub_category_id' => NULL,
                'base_unit' => 'case',
                'base_quantity' => 32,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '205.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '177.49',
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => '8',
                'attributes' => NULL,
                'created_at' => '2025-12-24 20:04:04',
                'updated_at' => '2025-12-24 20:04:04',
            ),
            3 => 
            array (
                'id' => 6,
                'parent_id' => NULL,
                'name' => 'PREMIUM',
                'code' => NULL,
                'type' => 'variable',
                'category_id' => 3,
                'sub_category_id' => NULL,
                'base_unit' => 'dozen',
                'base_quantity' => 12,
                'mrp_per_unit' => NULL,
                'ptr_per_dozen' => NULL,
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => NULL,
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => NULL,
                'attributes' => '[]',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            4 => 
            array (
                'id' => 7,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15 PREMIUM SAND',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Sandal","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            5 => 
            array (
                'id' => 8,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15 PREMIUM PATC',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Patcholi","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            6 => 
            array (
                'id' => 9,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15 PREMIUMKAST',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Kasturi","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            7 => 
            array (
                'id' => 10,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15PREMIUM3 IN 1',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"3 in 1","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            8 => 
            array (
                'id' => 11,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15 PREMIUM4IN1',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"4 in 1","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            9 => 
            array (
                'id' => 12,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15 PREMIUMAGNI',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Agni","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            10 => 
            array (
                'id' => 13,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15 PREMIUMJAL',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Jal","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            11 => 
            array (
                'id' => 14,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15PREMIUMAKASH',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Akash","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            12 => 
            array (
                'id' => 15,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15 PREMIUMVAYU',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Vayu","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            13 => 
            array (
                'id' => 16,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15PREMIUMPRITHIVI',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Prithivi","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            14 => 
            array (
                'id' => 17,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15PREMIUMSHAKTIPEETH',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Shakti Peeth","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            15 => 
            array (
                'id' => 18,
                'parent_id' => 6,
                'name' => NULL,
                'code' => '15PREMIUMSIDDHIVINAYAK',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '96.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '83.12',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Siddhi Vinayak","size":"9"}',
                'created_at' => '2025-12-24 20:14:42',
                'updated_at' => '2025-12-24 20:14:42',
            ),
            16 => 
            array (
                'id' => 19,
                'parent_id' => NULL,
                'name' => 'Prarthana',
                'code' => NULL,
                'type' => 'variable',
                'category_id' => 1,
                'sub_category_id' => NULL,
                'base_unit' => 'dozen',
                'base_quantity' => 12,
                'mrp_per_unit' => NULL,
                'ptr_per_dozen' => NULL,
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => NULL,
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => NULL,
                'attributes' => '[]',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            17 => 
            array (
                'id' => 20,
                'parent_id' => 19,
                'name' => NULL,
                'code' => '15 PRARTHANALEV',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '92.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '79.65',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Lavender","size":"9"}',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            18 => 
            array (
                'id' => 21,
                'parent_id' => 19,
                'name' => NULL,
                'code' => '15 PRARTHANARAJ',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '92.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '79.65',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Rajanigandha","size":"9"}',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            19 => 
            array (
                'id' => 22,
                'parent_id' => 19,
                'name' => NULL,
                'code' => '15 PRARTHANAPINE',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '92.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '79.65',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Pineapple","size":"9"}',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            20 => 
            array (
                'id' => 23,
                'parent_id' => 19,
                'name' => NULL,
                'code' => '15 PRARTHANAMOG',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '92.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '79.65',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Mogra","size":"9"}',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            21 => 
            array (
                'id' => 24,
                'parent_id' => 19,
                'name' => NULL,
                'code' => '15PRARTHANAMANTHAN',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '92.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '79.65',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Manthan","size":"9"}',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            22 => 
            array (
                'id' => 25,
                'parent_id' => 19,
                'name' => NULL,
                'code' => '15PRARTHANASPARSH',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '92.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '79.65',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Sparsh","size":"9"}',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            23 => 
            array (
                'id' => 26,
                'parent_id' => 19,
                'name' => NULL,
                'code' => '15PRARTHANAPRAKRITI',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '92.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '79.65',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Prakriti","size":"9"}',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            24 => 
            array (
                'id' => 27,
                'parent_id' => 19,
                'name' => NULL,
                'code' => '15PRARTHANASMARAN',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '15.00',
                'ptr_per_dozen' => '92.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '79.65',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '15.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Smaran","size":"9"}',
                'created_at' => '2025-12-24 20:23:21',
                'updated_at' => '2025-12-24 20:23:21',
            ),
            25 => 
            array (
                'id' => 28,
                'parent_id' => NULL,
                'name' => 'Aaradhya',
                'code' => NULL,
                'type' => 'variable',
                'category_id' => 5,
                'sub_category_id' => NULL,
                'base_unit' => 'dozen',
                'base_quantity' => 12,
                'mrp_per_unit' => NULL,
                'ptr_per_dozen' => NULL,
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => NULL,
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => NULL,
                'attributes' => '[]',
                'created_at' => '2025-12-24 20:26:55',
                'updated_at' => '2025-12-24 20:26:55',
            ),
            26 => 
            array (
                'id' => 29,
                'parent_id' => 28,
                'name' => NULL,
                'code' => '25 AARADHYACHAN',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '25.00',
                'ptr_per_dozen' => '190.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '164.50',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '50.00',
                'size' => '8',
                'attributes' => '{"fragrance":"Chandan","size":"8"}',
                'created_at' => '2025-12-24 20:26:55',
                'updated_at' => '2025-12-24 20:26:55',
            ),
            27 => 
            array (
                'id' => 30,
                'parent_id' => 28,
                'name' => NULL,
                'code' => '25 AARADHYAMOGR',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '25.00',
                'ptr_per_dozen' => '190.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '164.50',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '50.00',
                'size' => '8',
                'attributes' => '{"fragrance":"Mogra","size":"8"}',
                'created_at' => '2025-12-24 20:26:55',
                'updated_at' => '2025-12-24 20:26:55',
            ),
            28 => 
            array (
                'id' => 31,
                'parent_id' => 28,
                'name' => NULL,
                'code' => '25 AARADHYABELA',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '25.00',
                'ptr_per_dozen' => '190.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '164.50',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '50.00',
                'size' => '8',
                'attributes' => '{"fragrance":"Bela","size":"8"}',
                'created_at' => '2025-12-24 20:26:55',
                'updated_at' => '2025-12-24 20:26:55',
            ),
            29 => 
            array (
                'id' => 32,
                'parent_id' => 28,
                'name' => NULL,
                'code' => '25 AARADHYAKAST',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '25.00',
                'ptr_per_dozen' => '190.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '164.50',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '50.00',
                'size' => '8',
                'attributes' => '{"fragrance":"Kasturi","size":"8"}',
                'created_at' => '2025-12-24 20:26:55',
                'updated_at' => '2025-12-24 20:26:55',
            ),
            30 => 
            array (
                'id' => 33,
                'parent_id' => 28,
                'name' => NULL,
                'code' => '25 AARADHYAROSE',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '25.00',
                'ptr_per_dozen' => '190.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '164.50',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '50.00',
                'size' => '8',
                'attributes' => '{"fragrance":"Rose","size":"8"}',
                'created_at' => '2025-12-24 20:26:55',
                'updated_at' => '2025-12-24 20:26:55',
            ),
            31 => 
            array (
                'id' => 34,
                'parent_id' => NULL,
                'name' => 'Prarthana 100 GM',
                'code' => NULL,
                'type' => 'variable',
                'category_id' => 2,
                'sub_category_id' => NULL,
                'base_unit' => 'dozen',
                'base_quantity' => 12,
                'mrp_per_unit' => NULL,
                'ptr_per_dozen' => NULL,
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => NULL,
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => NULL,
                'attributes' => '[]',
                'created_at' => '2025-12-24 20:31:10',
                'updated_at' => '2025-12-24 20:31:10',
            ),
            32 => 
            array (
                'id' => 35,
                'parent_id' => 34,
                'name' => NULL,
                'code' => '60 PRARTHANAPIN',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '60.00',
                'ptr_per_dozen' => '415.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '359.31',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '100.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Pineapple","size":"9"}',
                'created_at' => '2025-12-24 20:31:10',
                'updated_at' => '2025-12-24 20:31:10',
            ),
            33 => 
            array (
                'id' => 36,
                'parent_id' => 34,
                'name' => NULL,
                'code' => '60 PRARTHANARAJ',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '60.00',
                'ptr_per_dozen' => '415.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '359.31',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '100.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Rajanigandha","size":"9"}',
                'created_at' => '2025-12-24 20:31:10',
                'updated_at' => '2025-12-24 20:31:10',
            ),
            34 => 
            array (
                'id' => 37,
                'parent_id' => 34,
                'name' => NULL,
                'code' => '60 PRARTHANAMOG',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '60.00',
                'ptr_per_dozen' => '415.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '359.31',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '100.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Mogra","size":"9"}',
                'created_at' => '2025-12-24 20:31:10',
                'updated_at' => '2025-12-24 20:31:10',
            ),
            35 => 
            array (
                'id' => 38,
                'parent_id' => 34,
                'name' => NULL,
                'code' => '60PRARTHANAMANTHAN',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '60.00',
                'ptr_per_dozen' => '415.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '359.31',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '100.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Manthan","size":"9"}',
                'created_at' => '2025-12-24 20:31:10',
                'updated_at' => '2025-12-24 20:31:10',
            ),
            36 => 
            array (
                'id' => 39,
                'parent_id' => 34,
                'name' => NULL,
                'code' => '60PRARTHANASPARSH',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '60.00',
                'ptr_per_dozen' => '415.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '359.31',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '100.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Sparsh","size":"9"}',
                'created_at' => '2025-12-24 20:31:10',
                'updated_at' => '2025-12-24 20:31:10',
            ),
            37 => 
            array (
                'id' => 40,
                'parent_id' => 34,
                'name' => NULL,
                'code' => '60PRARTHANASMARAN',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '60.00',
                'ptr_per_dozen' => '415.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '359.31',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '100.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Smaran","size":"9"}',
                'created_at' => '2025-12-24 20:31:10',
                'updated_at' => '2025-12-24 20:31:10',
            ),
            38 => 
            array (
                'id' => 41,
                'parent_id' => 34,
                'name' => NULL,
                'code' => '60 PRARTHANALEV',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '60.00',
                'ptr_per_dozen' => '415.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '359.31',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '100.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Lavender","size":"9"}',
                'created_at' => '2025-12-24 20:31:10',
                'updated_at' => '2025-12-24 20:31:10',
            ),
            39 => 
            array (
                'id' => 43,
                'parent_id' => 34,
                'name' => 'Prarthana 100 GM',
                'code' => '60PRARTHANAPRKRITI',
                'type' => 'variant',
                'category_id' => 2,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '60.00',
                'ptr_per_dozen' => '415.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '370.91',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '100.00',
                'size' => NULL,
                'attributes' => '{"fragrance":"Prakriti","size":"9"}',
                'created_at' => '2025-12-24 20:48:49',
                'updated_at' => '2025-12-24 20:48:49',
            ),
            40 => 
            array (
                'id' => 44,
                'parent_id' => NULL,
                'name' => 'Premium',
                'code' => NULL,
                'type' => 'variable',
                'category_id' => 4,
                'sub_category_id' => NULL,
                'base_unit' => 'dozen',
                'base_quantity' => 12,
                'mrp_per_unit' => NULL,
                'ptr_per_dozen' => NULL,
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => NULL,
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => NULL,
                'attributes' => '[]',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            41 => 
            array (
                'id' => 45,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMSAND',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Sandal","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            42 => 
            array (
                'id' => 46,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMPATC',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Patcholi","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            43 => 
            array (
                'id' => 47,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMKAST',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Kasturi","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            44 => 
            array (
                'id' => 48,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUM3 IN 1',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"3 in 1","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            45 => 
            array (
                'id' => 49,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUM4 IN 1',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"4 in 1","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            46 => 
            array (
                'id' => 50,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMAGNI',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Agni","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            47 => 
            array (
                'id' => 51,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMJAL',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Jal","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            48 => 
            array (
                'id' => 52,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMAKASH',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Akash","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            49 => 
            array (
                'id' => 53,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMVAYU',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Vayu","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            50 => 
            array (
                'id' => 54,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMPRITHIVI',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Prithvi","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            51 => 
            array (
                'id' => 55,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMSHAKTIPEETH',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Shakti Peeth","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            52 => 
            array (
                'id' => 56,
                'parent_id' => 44,
                'name' => NULL,
                'code' => '70PREMIUMSIDDHIVINAYAK',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '480.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '415.58',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '90.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Siddhi Vinayak","size":"9"}',
                'created_at' => '2025-12-24 20:55:05',
                'updated_at' => '2025-12-24 20:55:05',
            ),
            53 => 
            array (
                'id' => 57,
                'parent_id' => NULL,
                'name' => 'Premium Zipper 120gm',
                'code' => NULL,
                'type' => 'variable',
                'category_id' => 6,
                'sub_category_id' => NULL,
                'base_unit' => 'dozen',
                'base_quantity' => 12,
                'mrp_per_unit' => NULL,
                'ptr_per_dozen' => NULL,
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => NULL,
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => NULL,
                'attributes' => '[]',
                'created_at' => '2025-12-24 21:55:42',
                'updated_at' => '2025-12-24 21:55:42',
            ),
            54 => 
            array (
                'id' => 58,
                'parent_id' => 57,
                'name' => NULL,
                'code' => '70PREMIUMSAND',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '426.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '368.83',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '120.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Sandal","size":"9"}',
                'created_at' => '2025-12-24 21:55:42',
                'updated_at' => '2025-12-24 21:55:42',
            ),
            55 => 
            array (
                'id' => 59,
                'parent_id' => 57,
                'name' => NULL,
                'code' => '70PREMIUAGNI',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '426.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '368.83',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '120.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Agni","size":"9"}',
                'created_at' => '2025-12-24 21:55:42',
                'updated_at' => '2025-12-24 21:55:42',
            ),
            56 => 
            array (
                'id' => 60,
                'parent_id' => 57,
                'name' => NULL,
                'code' => '70PREMIUMKASTURI',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '70.00',
                'ptr_per_dozen' => '426.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '368.83',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '120.00',
                'size' => '9',
                'attributes' => '{"fragrance":"Kasturi","size":"9"}',
                'created_at' => '2025-12-24 21:55:42',
                'updated_at' => '2025-12-24 21:55:42',
            ),
            57 => 
            array (
                'id' => 61,
                'parent_id' => NULL,
                'name' => 'Premium Zipper Pack',
                'code' => NULL,
                'type' => 'variable',
                'category_id' => 7,
                'sub_category_id' => NULL,
                'base_unit' => 'dozen',
                'base_quantity' => 12,
                'mrp_per_unit' => NULL,
                'ptr_per_dozen' => NULL,
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => NULL,
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => NULL,
                'attributes' => '[]',
                'created_at' => '2025-12-24 21:56:33',
                'updated_at' => '2025-12-24 21:56:33',
            ),
            58 => 
            array (
                'id' => 62,
                'parent_id' => 61,
                'name' => NULL,
                'code' => '150POPULAR4IN1',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '150.00',
                'ptr_per_dozen' => '1155.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '1000.00',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '400.00',
                'size' => '9',
                'attributes' => '{"fragrance":"4 in 1","size":"9"}',
                'created_at' => '2025-12-24 21:56:33',
                'updated_at' => '2025-12-24 21:56:33',
            ),
            59 => 
            array (
                'id' => 63,
                'parent_id' => NULL,
                'name' => 'Popular Pouch',
                'code' => NULL,
                'type' => 'variable',
                'category_id' => 8,
                'sub_category_id' => NULL,
                'base_unit' => 'dozen',
                'base_quantity' => 12,
                'mrp_per_unit' => NULL,
                'ptr_per_dozen' => NULL,
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => NULL,
                'distributor_discount_percent' => NULL,
                'weight_gm' => NULL,
                'size' => NULL,
                'attributes' => '[]',
                'created_at' => '2025-12-24 21:57:16',
                'updated_at' => '2025-12-24 21:57:16',
            ),
            60 => 
            array (
                'id' => 64,
                'parent_id' => 63,
                'name' => NULL,
                'code' => '35POPULAR3IN1',
                'type' => 'variant',
                'category_id' => NULL,
                'sub_category_id' => NULL,
                'base_unit' => NULL,
                'base_quantity' => NULL,
                'mrp_per_unit' => '35.00',
                'ptr_per_dozen' => '205.00',
                'retailer_discount_percent' => NULL,
                'ptd_per_dozen' => '177.49',
                'distributor_discount_percent' => NULL,
                'weight_gm' => '80.00',
                'size' => '9',
                'attributes' => '{"fragrance":"3 in 1","size":"9"}',
                'created_at' => '2025-12-24 21:57:16',
                'updated_at' => '2025-12-24 21:57:16',
            ),
        ));
        
        
    }
}