<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // ✅ This is important

class SalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

DB::table('sales_persons')->insert([
            [
                'id' => 1,
                'name' => 'MAZIBUR RAHMAN',
                'designation' => 'T.S.M',
                'headquarter' => 'Guwahati',
                'address_line_1' => 'Mangaldai, Darrang (Assam )',
                'address_line_2' => null,
                'town' => 'Mangaldai',
                'district' => 'Darrang',
                'state' => 'Assam',
                'pincode' => '781011',
                'phone' => '6000366685',
                'official_email' => null,
                'personal_email' => 'rahman_mazibur@rediffmail.com',
                'date_of_birth' => '1978-01-21',
                'date_of_anniversary' => null,
                'zone' => 'Guwahati',
                'state_covered' => null,
                'district_covered' => null,
                'town_covered' => '',
                'profile_photo' => null,
                'login_id' => 'mazibur@prrahi.in',
                'password' => '$2y$12$Z83BmlbqwIE6AZ34RHK0D.C.wqOtcnkxnWBL9Fd2rivw.iKdTKP8y',
                'created_at' => '2025-07-28 13:55:44',
                'updated_at' => '2025-08-22 03:25:49',
            ],
            [
                'id' => 2,
                'name' => 'MAYUKH CHOUDHURY',
                'designation' => 'Territory Sales Manager',
                'headquarter' => 'Barak Valley',
                'address_line_1' => 'Janata lane,House No 9, Ward No 15, Sonai Road, Silchar',
                'address_line_2' => null,
                'town' => 'Silchar',
                'district' => 'Karimganj',
                'state' => 'Assam',
                'pincode' => '788005',
                'phone' => '9707371983',
                'official_email' => 'mayukh@prrahi.in',
                'personal_email' => 'mayukh.choudhury@yahoo.co.in',
                'date_of_birth' => '1983-04-11',
                'date_of_anniversary' => null,
                'zone' => null,
                'state_covered' => 'Assam',
                'district_covered' => null,
                'town_covered' => '',
                'profile_photo' => null,
                'login_id' => 'mayukh@prrahi.in',
                'password' => '$2y$12$U17iPOIX7OM0BnDF9cTUw.bec3INl/86oOQprVPfDvRXvdtXFBMeS',
                'created_at' => '2025-08-01 11:16:05',
                'updated_at' => '2025-08-08 20:02:16',
            ],
            [
                'id' => 3,
                'name' => 'JOYDIP DAS GUPTA',
                'designation' => 'Territory Sales Manager',
                'headquarter' => 'Tripura',
                'address_line_1' => 'Chandrapur, Dharamanagar North Tripura, India',
                'address_line_2' => null,
                'town' => 'Tripura',
                'district' => 'West Karbi Anglong',
                'state' => 'Assam',
                'pincode' => '799251',
                'phone' => '8787319593',
                'official_email' => 'joydip@prrahi.in',
                'personal_email' => 'joyrock2014.jd@gmail.com',
                'date_of_birth' => '1985-10-30',
                'date_of_anniversary' => null,
                'zone' => null,
                'state_covered' => null,
                'district_covered' => null,
                'town_covered' => null,
                'profile_photo' => null,
                'login_id' => 'joydip@prrahi.in',
                'password' => '$2y$12$ZCBKDRc58wcTcCK8EVDfvOO5cIUmTBGeWQWaZN5Y6Nbt3oHnPUjDO',
                'created_at' => '2025-08-01 12:07:04',
                'updated_at' => '2025-08-01 12:07:04',
            ],
            [
                'id' => 4,
                'name' => 'KRISHNA DAS',
                'designation' => 'Territory Sales Manager',
                'headquarter' => 'Nagaon',
                'address_line_1' => 'Panigaon Santiban, Nagaon',
                'address_line_2' => null,
                'town' => 'Nagaon',
                'district' => 'Nagaon',
                'state' => 'Assam',
                'pincode' => '782001',
                'phone' => '7005547476',
                'official_email' => 'krishna@prrahi.in',
                'personal_email' => 'krishnadas392@gmai.com',
                'date_of_birth' => '1982-02-19',
                'date_of_anniversary' => null,
                'zone' => null,
                'state_covered' => 'Assam',
                'district_covered' => 'Hojai,Sonitpur',
                'town_covered' => null,
                'profile_photo' => null,
                'login_id' => 'krishna@prrahi.in',
                'password' => '$2y$12$PHE6QZwPqN18RIUYepjlBOXj65eiBC9VjnpEFke3Iol.4GAo4PsfG',
                'created_at' => '2025-08-01 12:14:10',
                'updated_at' => '2025-08-01 12:14:10',
            ],
            [
                'id' => 5,
                'name' => 'RAJESH PAUL',
                'designation' => 'Territory Sales Manager',
                'headquarter' => 'Dibrugarh',
                'address_line_1' => 'Santipara,TS Lane, Dibrugarh',
                'address_line_2' => null,
                'town' => 'Dibrugarh',
                'district' => 'Dibrugarh',
                'state' => 'Assam',
                'pincode' => '786001',
                'phone' => '8011632485',
                'official_email' => 'rajesh@prrahi.in',
                'personal_email' => 'rajesh.ceepee16@gmail.com',
                'date_of_birth' => '1978-05-01',
                'date_of_anniversary' => '2006-04-16',
                'zone' => null,
                'state_covered' => null,
                'district_covered' => null,
                'town_covered' => null,
                'profile_photo' => null,
                'login_id' => 'rajesh@prrahi.in',
                'password' => '$2y$12$/ZzHKWNMpXZfLgv.7wPOeeBcwyCDkCxggKUOVJeTfOOnuL.YrKAEW',
                'created_at' => '2025-08-01 12:31:54',
                'updated_at' => '2025-08-01 12:31:54',
            ],
            [
                'id' => 6,
                'name' => 'TAPAN DEBNATH',
                'designation' => 'Territory Sales Manager',
                'headquarter' => 'Jorhat',
                'address_line_1' => 'West Sripuria, Zigzag Road, Tinsukia',
                'address_line_2' => null,
                'town' => '786125',
                'district' => 'Tinsukia',
                'state' => 'Assam',
                'pincode' => '786125',
                'phone' => '8822690802',
                'official_email' => 'tapan@prrahi.in',
                'personal_email' => 'tap84an@rediffmail.com',
                'date_of_birth' => '1984-03-21',
                'date_of_anniversary' => null,
                'zone' => null,
                'state_covered' => 'Assam',
                'district_covered' => null,
                'town_covered' => null,
                'profile_photo' => null,
                'login_id' => 'tapan@prrahi.com',
                'password' => '$2y$12$aSfgRNQ8PevGCJutLNhL..fKGQ7HZqogjyB2Vj2ndvG6w9j6qGthe',
                'created_at' => '2025-08-01 13:02:44',
                'updated_at' => '2025-08-01 13:02:44',
            ],
        ]);



    }




}
